site_name: Apocryphal Stone
theme:
  name: readthedocs

nav:
  - Home: index.md
  # Example: Include a static HTML file in the navigation
  - test: test.html

extra_css: 
  - assets/css/extra.css

# If you use any plugins, list them here
plugins:
  - search

# If you need any specific Markdown extensions, list them here
markdown_extensions:
  - toc
  - fenced_code
  - tables