site_name: Apocryphal Stone
theme:
  name: readthedocs

nav:
  - Home: index.html
  - Bibliography: bibliography.html
  - Poetry: poetry.html
  - Contact: contact.html

extra_css: 
  - assets/css/extra.css

# If you use any plugins, list them here
plugins:
  - search

# If you need any specific Markdown extensions, list them here
markdown_extensions:
  - toc
  - fenced_code
  - tables