site_name: Apocryphal Stone
theme:
  name: readthedocs

nav:
  - Home: index.html
  - Bibliography: bibliography.html
  - Links: links.html
  - Contact: contact.html
  - News: news.html
  - bibliography:
    - index:
      - Bibliograph_page:
        - "2": 2.html
        - "3": 3.html
        - "4": 4.html
        - "5": 5.html
        - "6": 6.html
    - "1": 1.html
    - "5": 5.html
    - "9": 9.html
    - "12": 12.html
    - "17": 17.html
    - "19": 19.html
    - "20": 20.html
    - "28": 28.html
    - "64": 64.html
    - "67": 67.html
    - "82": 82.html
    - "86": 86.html
    - "95": 95.html
    - "116": 116.html
    - "119": 119.html
    - "132": 132.html
    - "136": 136.html
    - "140": 140.html
    - "153": 153.html
    - "154": 154.html
    - "162": 162.html
    - "163": 163.html
    - "164": 164.html
    - "165": 165.html
    - "170": 170.html
    - "174": 174.html
    - "184": 184.html
    - "186": 186.html
    - "192": 192.html
    - "198": 198.html
    - "206": 206.html
    - "207": 207.html
    - "208": 208.html
    - "210": 210.html
    - "212": 212.html
    - "217": 217.html
    - "219": 219.html
    - "221": 221.html
    - "225": 225.html
    - "226": 226.html
    - "230": 230.html
    - "233": 233.html
    - "234": 234.html
    - "235": 235.html
    - "237": 237.html
    - "238": 238.html
    - "243": 243.html
    - "244": 244.html
    - "246": 246.html
    - "248": 248.html
    - "249": 249.html
    - "252": 252.html
    - "253": 253.html
    - "254": 254.html
    - "256": 256.html
    - "257": 257.html
    - "258": 258.html
    - "259": 259.html
    - "260": 260.html
    - "261": 261.html
    - "262": 262.html
    - "263": 263.html
    - "264": 264.html
    - "265": 265.html
    - "266": 266.html
    - "267": 267.html
    - "268": 268.html
    - "269": 269.html
    - "270": 270.html
    - "271": 271.html
    - "272": 272.html
    - "274": 274.html
    - "275": 275.html
    - "277": 277.html
    - "279": 279.html
    - "280": 280.html
    - "281": 281.html
    - "282": 282.html
    - "283": 283.html
    - "284": 284.html
    - "285": 285.html
    - "286": 286.html
    - "287": 287.html
    - "288": 288.html
    - "289": 289.html
    - "291": 291.html
    - "294": 294.html
    - "295": 295.html
    - "296": 296.html
    - "297": 297.html
    - "298": 298.html
    - "299": 299.html
    - "300": 300.html
    - "301": 301.html
    - "302": 302.html
    - "303": 303.html
    - "306": 306.html
    - "307": 307.html
    - "308": 308.html
    - "309": 309.html
    - "310": 310.html
    - "311": 311.html
    - "312": 312.html
    - "315": 315.html
    - "316": 316.html
    - "317": 317.html
    - "318": 318.html
    - "319": 319.html
    - "320": 320.html
    - "321": 321.html
    - "322": 322.html
    - "323": 323.html
    - "324": 324.html
    - "325": 325.html
    - "326": 326.html
    - "327": 327.html
    - "328": 328.html
    - "330": 330.html
    - "331": 331.html
    - "332": 332.html
    - "333": 333.html
    - "334": 334.html
    - "336": 336.html
    - "339": 339.html
    - "341": 341.html
    - "342": 342.html
    - "347": 347.html
    - "356": 356.html
    - "359": 359.html
    - "360": 360.html
    - "384": 384.html
    - "1001": 1001.html
    - "1004": 1004.html
    - "1005": 1005.html
    - "1007": 1007.html
    - "1008": 1008.html
    - "1021": 1021.html
    - "1031": 1031.html
    - "1034": 1034.html

extra_css: 
  - assets/css/extra.css

# If you use any plugins, list them here
plugins:
  - search

# If you need any specific Markdown extensions, list them here
markdown_extensions:
  - toc
  - fenced_code
  - tables